# Generated by Django 5.2.3 on 2025-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramm'), ('pcs', 'Dona')], default='kg', max_length=3, verbose_name='Birlik'),
        ),
    ]
